<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Certificat_model');
        $this->load->model('User_model');
        $this->load->model('History_model');

        if(!isset($_SESSION['user_logged'])){
            $this->session->set_flashdata('error','connecter !!!!');
            redirect('user/login');
        }

    } 


    function index()
    {
        $data['histories'] =  $this->History_model->get_all_history();
        $data['certificats'] = $this->Certificat_model->get_all_certificats();

        $data['users'] = $this->User_model->get_all_users();
        $data['benificiares'] = $this->User_model->get_benificiares();
        
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
        
    }
}
