<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Montant_item extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Montant_item_model');
        $this->load->model('Label_model');
        $this->load->model('Certificat_model');
        
        if(!isset($_SESSION['user_logged'])){
            $this->session->set_flashdata('error','connecter !!!!');
            redirect('user/login');
        }

    } 

    /*
     * Listing of montant_items
     */
    function index()
    {
        $data['montant_items'] = $this->Montant_item_model->get_all_montant_items();
        
        $data['_view'] = 'montant_item/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new montant_item
     */
    function add()
    {   
 
        if(isset($_POST) && count($_POST) > 0)     
        {   
            // $params = array(
			// 	'montant_brut' => $this->input->post('montant_brut'),
			// 	'retenue' => $this->input->post('retenue'),
			// 	'montant_net' => $this->input->post('montant_net'),
			// 	'label_id' => $this->input->post('label_id'),
            // );
            
            // $montant_item_id = $this->Montant_item_model->add_montant_item($params);
            // $label = $this->Label_model->get_label($params['label_id']);


            $counter = $_POST['counter'];
            for($i=0;$i<=$counter;$i++){

                $params2 = array(
                    'montant_brut' => $this->input->post('montant_brut'.$i),
                    'retenue' => $this->input->post('retenue'.$i),
                    'montant_net' => $this->input->post('montant_net'.$i),
                    'label_id' => $this->input->post('label_id'.$i),
                );
                $montant_item_id = $this->Montant_item_model->add_montant_item($params2);

            }

            // redirect('certificat/detail/'.$label['certif_id']);            
        }
        else
        {      
            $data['labels'] = $this->Label_model->get_all_labels();
            $data['certificats'] = $this->Certificat_model->get_all_certificats();
            
            $data['_view'] = 'montant_item/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a montant_item
     */
    function edit($id_montant_items)
    {   
        // check if the montant_item exists before trying to edit it
        $data['montant_item'] = $this->Montant_item_model->get_montant_item($id_montant_items);
        $data['label'] = $this->Label_model->get_label($this->Montant_item_model->get_montant_item($id_montant_items)['label_id']);

        if(isset($data['montant_item']['id_montant_items']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'montant_brut' => $this->input->post('montant_brut'),
					'retenue' => $this->input->post('retenue'),
					'montant_net' => $this->input->post('montant_net'),
					'label_id' => $this->input->post('label_id'),
                );

                $this->Montant_item_model->update_montant_item($id_montant_items,$params);            
                 $label = $this->Label_model->get_label($params['label_id']);
                redirect('certificat/detail/'.$label['certif_id']);
            }
            else
            {
                $data['labels'] = $this->Label_model->get_all_labels();
 
                $data['_view'] = 'montant_item/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The montant_item you are trying to edit does not exist.');
    } 

    /*
     * Deleting montant_item
     */
    function remove($id_montant_items)
    {
        $montant_item = $this->Montant_item_model->get_montant_item($id_montant_items);

        // check if the montant_item exists before trying to delete it
        if(isset($montant_item['id_montant_items']))
        {
            $this->Montant_item_model->delete_montant_item($id_montant_items);
            $label = $this->Label_model->get_label($montant_item['label_id']);
            redirect('certificat/detail/'.$label['certif_id']);
        }
        else
            show_error('The montant_item you are trying to delete does not exist.');
    }
    
}
