<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Certificat_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get certificat by idcertif
     */
    function get_certificat($idcertif)
    {
        return $this->db->get_where('certificats',array('idcertif'=>$idcertif))->row_array();
    }
        
    function get_certif_labels($idcertif)
    {
        $this->db->select('labels.id_label, labels.label_text, montant_items.id_montant_items, montant_items.montant_brut, montant_items.retenue, montant_items.montant_net');
        $this->db->from('labels');
        $this->db->join('certificats', 'labels.certif_id = certificats.idcertif');
        $this->db->join('montant_items', 'montant_items.label_id = labels.id_label', 'left');
        $this->db->where('labels.certif_id', $idcertif);

        return $this->db->get()->result_array();
    }

    function get_certificate_labels($idcertif)
    {
        $this->db->select('labels.*');
        $this->db->from('labels');
        $this->db->join('certificats', 'labels.certif_id = certificats.idcertif','left');
         $this->db->where('labels.certif_id', $idcertif);

        return $this->db->get()->result_array();
    }
 

        

    /*
     * Get all certificats
     */
    function get_all_certificats()
    {
        $this->db->order_by('idcertif', 'desc');
        return $this->db->get('certificats')->result_array();
    }

    function get_user_certificats($userid)
    {
        $this->db->select('certificats.*');
        $this->db->from('certificats');
        $this->db->join('history', 'certificats.idcertif = history.certif_id', 'left');
        $this->db->where('history.user_id', $userid);

        return $this->db->get()->result_array();
    }


    function get_certif_user($idcertif)
    {
        $this->db->select('users.*');
        $this->db->from('users');
        $this->db->join('history', 'users.userid = history.user_id', 'left');
        $this->db->join('certificats', 'history.certif_id = certificats.idcertif', 'left');
        // $this->db->where('history.certif_id', $idcertif);

        return $this->db->get()->row_array();
    }
    /*
     * function to add new certificat
     */
    function add_certificat($params)
    {
        $this->db->insert('certificats',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update certificat
     */
    function update_certificat($idcertif,$params)
    {
        $this->db->where('idcertif',$idcertif);
        return $this->db->update('certificats',$params);
    }
    
    /*
     * function to delete certificat
     */
    function delete_certificat($idcertif)
    {
        return $this->db->delete('certificats',array('idcertif'=>$idcertif));
    }
}
