<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Label_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get label by id_label
     */
    function get_label($id_label)
    {
        return $this->db->get_where('labels',array('id_label'=>$id_label))->row_array();
    }
        
    /*
     * Get all labels
     */
    function get_all_labels()
    {
        $this->db->order_by('id_label', 'desc');
        return $this->db->get('labels')->result_array();
    }
        
    /*
     * function to add new label
     */
    function add_label($params)
    {
        $this->db->insert('labels',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update label
     */
    function update_label($id_label,$params)
    {
        $this->db->where('id_label',$id_label);
        return $this->db->update('labels',$params);
    }
    
    /*
     * function to delete label
     */
    function delete_label($id_label)
    {
        return $this->db->delete('labels',array('id_label'=>$id_label));
    }
}
