<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Montant_item_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get montant_item by id_montant_items
     */
    function get_montant_item($id_montant_items)
    {
        return $this->db->get_where('montant_items',array('id_montant_items'=>$id_montant_items))->row_array();
    }
        
    /*
     * Get all montant_items
     */
    function get_all_montant_items()
    {
        $this->db->order_by('id_montant_items', 'desc');
        return $this->db->get('montant_items')->result_array();
    }
        
    /*
     * function to add new montant_item
     */
    function add_montant_item($params)
    {
        $this->db->insert('montant_items',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update montant_item
     */
    function update_montant_item($id_montant_items,$params)
    {
        $this->db->where('id_montant_items',$id_montant_items);
        return $this->db->update('montant_items',$params);
    }
    
    /*
     * function to delete montant_item
     */
    function delete_montant_item($id_montant_items)
    {
        return $this->db->delete('montant_items',array('id_montant_items'=>$id_montant_items));
    }
}
